version: "3.10"
services:
  database:
    image: postgres:latest
    privileged: true
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    ports:
      - "5433:5432"
    volumes:
      - '/docker-data/database/:/var/lib/postgresql/data:z'

volumes:
  postgres_data: